# Generated by Django 3.1.3 on 2020-12-10 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201113_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsetting',
            name='allow_discusstion',
        ),
        migrations.AddField(
            model_name='postsetting',
            name='allow_discussion',
            field=models.BooleanField(default=True, verbose_name='allow discussion'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='blog.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='postsetting',
            name='author',
            field=models.BooleanField(default=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='postsetting',
            name='comment',
            field=models.BooleanField(default=True, verbose_name='comment'),
        ),
    ]
